### PR TITLE
Update and document compilation process

### PR DESCRIPTION
**Pull request by winksaville**
Add missing files and update README.md.

Update .gitignore to not ignore files that are now checked into git.

### CODE REVIEW

**Comment by winksaville** [comment]
I think this make life a little easier, please test and verify it works for you.

After this I'll try to use a submodule for Perspective and see if that works and then you can decide
if you'd like to me try to use submodules for other dependencies.

**Comment by stuartmscott** [comment]
Hey Wink thanks for the PR!

The gradle stuff should be checked into the repo and the documentation changes look good to go too. I am concerned about the aars and the jars under app/libs as these are build artifacts from other projects which aren't normally checked into repos and perhaps instead be available as "releases" in their respective projects.

My current setup, which admittedly is not perfect, uses symlinks to link the aars and jars to the outputs from their respective projects so as each project is built the changes are available to the others immediately. This change breaks such symlinks and would require the aars and jars to be copied from the other projects after each build. Maybe submodules would fix this but I don't have as much experience with them as you do - can a project such as AletheiaWareCommon be a submodule of both Perspective and SPACE? Alternatively the readme could contain info about setting up the symlinks or downloading from the releases page.

For now let's split this PR in two so we can get the gradle and readme changes in now and continue iterating on the best solution for the other dependancies.

Instead of the .gitignore commenting out the *.aar and *.jar rules, add the following to the bottom;

!/gradle/wrapper/gradle-wrapper.jar

**Comment by winksaville** [comment]
No longer needed.

**Comment by stuartmscott** [comment]
There were some valuable README.md changes in this, perhaps the Android Studio Prerequisite, and the Gradle examples could make their way into the README through a separate PR? The Arch Linux termcap issue should be documented incase future coders encounter it, albeit not in the README.md

**Comment by winksaville** [comment]
I've deleted all of the repos I'd forked to clean things on my side, but I've grabed this README.md and saved it locally and will create a PR as you suggest.

For the Arch Linux termcap issue I can make a page in the wiki in, `PerspectiveSuite`. On the other hand it's really a `gradle` issue that can/will effect any project using `gradle`, it seems it should be documented in a AletheiaWareLLC wiki, but that doesn't seem to be an option in github.

Your thoughts?

**Comment by stuartmscott** [comment]
Cool, thanks.

How about putting it in AletheiaWareCommonAndroid's wiki?

**Comment by winksaville** [comment]
AletheiaWareCommonAndroid it is, that currently the first one that uses `gradle`.

I know zero about `gradle`, could it be used instead of `build.sh` and then any `gradle` issues would "fail fast". Actually, could we start with just a `build.gradle` in `PerspectiveSuite` that does nothing more than execute `build.sh` to start?

**Comment by stuartmscott** [comment]
I've only used Gradle in the context of Android Studio, and even then most of it was generated for me.

**Comment by winksaville** [comment]
I'll take a quick look and see if we can use it to invoke build.sh or instead of build.sh.

Another gradle question, I built PerspectiveSuite cdfrom scratch this AM and ended up with tow differen versions, 5.4.1 and 5.1.1:
```
wink@wink-desktop:~/prgs/AletheiaWareLLC/PerspectiveSuite (master)
$ ls AletheiaWareCommonAndroid/.gradle/
5.4.1  buildOutputCleanup  vcs-1
wink@wink-desktop:~/prgs/AletheiaWareLLC/PerspectiveSuite (master)
$ ls JoyAndroid/.gradle/
5.1.1  buildOutputCleanup  vcs-1
wink@wink-desktop:~/prgs/AletheiaWareLLC/PerspectiveSuite (master)
$ ls PerspectiveAndroid/.gradle/
5.4.1  buildOutputCleanup  vcs-1
```
As I use Arch Linux, which is a "rolling relase" distro, I generally am using the "latest" code, so installed on my system is 5.6.2. I think we should standard on them all being the same, if possible. I vote for 5.6.2. What ya think?

Actually, what is your developement environment linux, mac, windows?

**Comment by stuartmscott** [comment]
JoyAndroid was behind, I updated it to Gradle 5.4.1 and the plugin to 3.5.0.

I'm using mac, though I don't have Gradle installed, I just use the wrapper which I'll update to 5.6.2.

**Comment by winksaville** [comment]
SG

**Pull request closed without merging**
